name: OCI ARM Auto Scraper

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Create Private Key File
        run: |
          echo "${{ secrets.OCI_KEY_CONTENT }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Run OCI Capacity Bot
        env:
          OCI_USER_ID: ${{ secrets.OCI_USER_OCID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_PRIVATE_KEY_FILENAME: 'private_key.pem'
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: 'ocid1.image.oc1.eu-frankfurt-1.aaaaaaaaqvd3uqw4f2sp3x6k3qf6znd5l3a6f4sxywzrq6jrg'
          OCI_AVAILABILITY_DOMAIN: ''
          OCI_SHAPE: 'VM.Standard.A1.Flex'
          OCI_OCPUS: '4'
          OCI_MEMORY_IN_GBS: '24'
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
        run: php index.php
